// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteContacts(arg1) {
  return window['go']['main']['App']['DeleteContacts'](arg1);
}

export function ExportCSV(arg1, arg2) {
  return window['go']['main']['App']['ExportCSV'](arg1, arg2);
}

export function GetContact(arg1) {
  return window['go']['main']['App']['GetContact'](arg1);
}

export function GetContacts(arg1) {
  return window['go']['main']['App']['GetContacts'](arg1);
}

export function AddContactToGroup(arg1, arg2) {
  return window['go']['main']['App']['AddContactToGroup'](arg1, arg2);
}

export function DeleteGroup(arg1) {
  return window['go']['main']['App']['DeleteGroup'](arg1);
}

export function GetContactGroups(arg1) {
  return window['go']['main']['App']['GetContactGroups'](arg1);
}

export function GetGroups() {
  return window['go']['main']['App']['GetGroups']();
}

export function RemoveContactFromGroup(arg1, arg2) {
  return window['go']['main']['App']['RemoveContactFromGroup'](arg1, arg2);
}

export function SaveGroup(arg1) {
  return window['go']['main']['App']['SaveGroup'](arg1);
}

export function ImportCSV(arg1) {
  return window['go']['main']['App']['ImportCSV'](arg1);
}

export function LookupPostal(arg1) {
  return window['go']['main']['App']['LookupPostal'](arg1);
}

export function OpenCSVFileDialog() {
  return window['go']['main']['App']['OpenCSVFileDialog']();
}

export function SaveCSVFileDialog(arg1) {
  return window['go']['main']['App']['SaveCSVFileDialog'](arg1);
}

export function SaveContact(arg1) {
  return window['go']['main']['App']['SaveContact'](arg1);
}

export function SearchContacts(arg1) {
  return window['go']['main']['App']['SearchContacts'](arg1);
}
