// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entity} from '../models';

export function DeleteContacts(arg1:Array<string>):Promise<void>;

export function GetContact(arg1:string):Promise<entity.Contact>;

export function GetContacts(arg1:string):Promise<Array<entity.Contact>>;

export function GetGroups():Promise<Array<entity.Group>>;

export function SaveContact(arg1:entity.Contact):Promise<entity.Contact>;

export function SearchContacts(arg1:string):Promise<Array<entity.Contact>>;
