// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entity} from '../models';

export function AddContactToGroup(arg1:string,arg2:string):Promise<void>;

export function AnalyzeCSVImport(arg1:string,arg2:Record<string, number>):Promise<entity.CSVImportAnalysis>;

export function ApplyAddressNormalization(arg1:Array<entity.AddressNormalizationSelection>):Promise<entity.AddressNormalizationApplyResult>;

export function CheckUnsupportedCharacters(arg1:entity.PrintJob):Promise<Array<entity.UnsupportedCharacterWarning>>;

export function DeleteContacts(arg1:Array<string>):Promise<void>;

export function DeleteGroup(arg1:string):Promise<void>;

export function DeleteSender(arg1:string):Promise<void>;

export function DeleteWatermark(arg1:string):Promise<void>;

export function ExportCSV(arg1:Array<string>,arg2:string):Promise<void>;

export function ExportDB():Promise<string>;

export function GenerateLabelPDF(arg1:entity.PrintJob,arg2:string):Promise<string>;

export function GenerateQRPreview(arg1:entity.QRConfig):Promise<Array<number>>;

export function GetAddressNormalizationPreview():Promise<entity.AddressNormalizationPreview>;

export function GetAppVersion():Promise<string>;

export function GetBackupSettings():Promise<entity.BackupSettings>;

export function GetCSVImportPlan(arg1:string):Promise<entity.CSVImportPlan>;

export function GetContact(arg1:string):Promise<entity.Contact>;

export function GetContactGroups(arg1:string):Promise<Array<entity.Group>>;

export function GetContacts(arg1:string):Promise<Array<entity.Contact>>;

export function GetDashboardStats():Promise<entity.DashboardStats>;

export function GetGroups():Promise<Array<entity.Group>>;

export function GetPrintHistory(arg1:number):Promise<Array<entity.PrintHistory>>;

export function GetSenders():Promise<Array<entity.Sender>>;

export function GetTempPDFPath():Promise<string>;

export function GetWatermarkPresets():Promise<Array<entity.Watermark>>;

export function ImportCSV(arg1:string):Promise<entity.ImportResult>;

export function ImportCSVWithOptions(arg1:string,arg2:Record<string, number>,arg3:Array<entity.CSVDuplicateResolution>):Promise<entity.CSVImportExecutionResult>;

export function ImportDB():Promise<boolean>;

export function ListBackupGenerations():Promise<Array<entity.BackupGeneration>>;

export function LookupPostal(arg1:string):Promise<entity.Address>;

export function OpenCSVFileDialog():Promise<string>;

export function PrintPDF(arg1:string):Promise<void>;

export function RemoveContactFromGroup(arg1:string,arg2:string):Promise<void>;

export function RestoreBackupGeneration(arg1:string):Promise<entity.RestoreBackupResult>;

export function RollbackAddressNormalization(arg1:string):Promise<entity.AddressNormalizationRollbackResult>;

export function SaveBackupSettings(arg1:entity.BackupSettings):Promise<entity.BackupSettings>;

export function SaveCSVFileDialog(arg1:string):Promise<string>;

export function SaveContact(arg1:entity.Contact):Promise<entity.Contact>;

export function SaveGroup(arg1:entity.Group):Promise<entity.Group>;

export function SavePDFFileDialog(arg1:string):Promise<string>;

export function SaveSender(arg1:entity.Sender):Promise<entity.Sender>;

export function SearchContacts(arg1:string):Promise<Array<entity.Contact>>;

export function SetContactGroups(arg1:string,arg2:Array<string>):Promise<void>;

export function SetDefaultSender(arg1:string):Promise<void>;

export function UploadWatermark(arg1:string):Promise<entity.Watermark>;
