// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteContacts(arg1) {
  return window['go']['main']['App']['DeleteContacts'](arg1);
}

export function GetContact(arg1) {
  return window['go']['main']['App']['GetContact'](arg1);
}

export function GetContacts(arg1) {
  return window['go']['main']['App']['GetContacts'](arg1);
}

export function SaveContact(arg1) {
  return window['go']['main']['App']['SaveContact'](arg1);
}

export function SearchContacts(arg1) {
  return window['go']['main']['App']['SearchContacts'](arg1);
}
